vorbestellen/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vorbestellenapp/', include('vorbestellenapp.urls', namespace='vorbestellenapp')), 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

vorbestellen/vorbestellen/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

vorbestellenapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.conf.urls import url
from django.urls import path
from vorbestellenapp import views

app_name = 'vorbestellenapp'

urlpatterns = [
    url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('', views.IndexView.as_view(), name="index_view"),
    path('logout/', views.logout, name='logout'),
    path('removefilter/', views.removefilter, name='removefilter'),
    path('removefilterbook/', views.removefilterbook, name='removefilterbook'),
    path('removefilterdate/', views.removefilterdate, name='removefilterdate'),
    path('about/', views.AboutView.as_view(), name="about_view"),
    path('contact/', views.ContactView.as_view(), name="contact_view"),
    path('admin/', views.AdminView.as_view(), name="admin_view"),
    path('pricing/', views.PriceView.as_view(), name="pricing_view"), 
    path('signup/', views.SignUpView.as_view(), name="signup_view"),
    path('account/', views.AccountView.as_view(), name="account_view"),
    path('rooms/', views.RoomsView.as_view(), name="rooms_view"),
    path('booking/', views.BookingView.as_view(), name="booking_view"),
    path('managebookings/', views.MngBkngsView.as_view(), name="managebookings_view"),
    path('manageusers/', views.MngUsersView.as_view(), name="manageusers_view"),
    path('vacantrooms/', views.VacantRoomsView.as_view(), name="vacantrooms_view"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vorbestellenapp/models.py
from django.db import models

class Users(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length = 20, unique=True)
    password = models.CharField(max_length = 256)
    email = models.CharField(max_length = 50)
    first_name = models.CharField(max_length = 50, default="Not set")
    last_name = models.CharField(max_length = 50, default="Not set")
    contact = models.CharField(max_length = 20, default="Not set")
    barangay = models.CharField(max_length = 20, default="Not set")
    city = models.CharField(max_length = 20, default="Not set")
    status = models.CharField(max_length = 20, default="Incomplete")

    class meta:
        db_table = 'Users'

    def __str__(self):
        return self.username

class Rooms(models.Model):
    room_code = models.AutoField(primary_key=True)
    room_name = models.CharField(max_length = 20, unique=True)
    room_type = models.CharField(max_length = 20)
    image = models.ImageField(upload_to='images', null=True)

    class meta:
        db_table = 'Rooms'

    def __str__(self):
        return self.room_code

class Reservations(models.Model):
    reservation_id = models.AutoField(primary_key=True)
    room_name = models.ForeignKey(Rooms,to_field='room_name',on_delete = models.CASCADE)
    reserver_id = models.ForeignKey(Users,to_field='username',on_delete = models.CASCADE)
    contact = models.CharField(max_length = 20)
    time = models.CharField(max_length = 20)
    date = models.CharField(max_length = 50)
    reserver = models.CharField(max_length = 50)
    status = models.CharField(max_length = 20, default="Pending")
    payment = models.FloatField() 

    class meta:
        db_tale = 'Reservations'

vorbestellenapp/forms.py
from django import forms
from .models import *

class UsersForm(forms.ModelForm):
    class Meta:
        model = Users
        exclude = ['first_name', 'last_name', 'contact','barangay','city','status']

class RoomsForm(forms.ModelForm):
    class Meta:
        model = Rooms
        exclude = ['room_name', 'room_type', 'image']

class ReservationsForm(forms.ModelForm):
    class Meta:
        model = Reservations
        exclude = ['status']

vorbestellenapp/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic import View
from .forms import *
from .models import *
from passlib.hash import pbkdf2_sha256
from django.db.models import Q
from django.core import serializers
from django.http import JsonResponse
from django.db.models import Count

def logout(request):
    try:
        del request.session['user']
    except:
        return redirect('vorbestellenapp:index_view')
    return redirect('vorbestellenapp:index_view')

def removefilter(request):
    try:
        del request.session['filtertrigger']
    except:
        return redirect('vorbestellenapp:vacantrooms_view')
    return redirect('vorbestellenapp:vacantrooms_view')

def removefilterbook(request):
    try:
        del request.session['filtertriggerbook']
    except:
        return redirect('vorbestellenapp:vacantrooms_view')
    return redirect('vorbestellenapp:vacantrooms_view')

def removefilterdate(request):
    try:
        del request.session['filterbookdate']
    except:
        return redirect('vorbestellenapp:vacantrooms_view')
    return redirect('vorbestellenapp:vacantrooms_view')

class IndexView(View): 
    def get(self, request): 
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.filter(username=current_user)     

            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'Index.html', context)
        else: 
            return render(request, 'Index.html', {})
            
    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            check_password = pbkdf2_sha256.hash(password, rounds=20000, salt_size=16)
            dec_password = pbkdf2_sha256.verify(password, check_password)
            check_user = Users.objects.filter(username=username)
            if check_user and dec_password:
                request.session['user'] = username
                if Users.objects.filter(username=username).count()>0:
                    return redirect('vorbestellenapp:index_view')
            else:
                messages.info(request, 'Incorrect Username and Password!', extra_tags='login')
                return redirect('vorbestellenapp:index_view')
        return redirect('vorbestellenapp:index_view')
            

class AboutView(View): 
    def get(self, request): 
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.filter(username=current_user)       

            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'About.html', context)
        else:
            return render(request, 'About.html', {})
        
    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            check_password = pbkdf2_sha256.hash(password, rounds=20000, salt_size=16)
            dec_password = pbkdf2_sha256.verify(password, check_password)
            check_user = Users.objects.filter(username=username)
            if check_user and dec_password:
                request.session['user'] = username
                if Users.objects.filter(username=username).count()>0:
                    return redirect('vorbestellenapp:about_view')
            else:
                messages.info(request, 'Incorrect Username and Password!', extra_tags='login')
                return redirect('vorbestellenapp:about_view')
        return redirect('vorbestellenapp:about_view')
        
class ContactView(View): 
    def get(self, request): 
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.filter(username=current_user)  

            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'Contact.html', context)
        else:
            return render(request, 'Contact.html', {})

    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            check_password = pbkdf2_sha256.hash(password, rounds=20000, salt_size=16)
            dec_password = pbkdf2_sha256.verify(password, check_password)
            check_user = Users.objects.filter(username=username)
            if check_user and dec_password:
                request.session['user'] = username
                if Users.objects.filter(username=username).count()>0:
                    return redirect('vorbestellenapp:contact_view')
            else:
                messages.info(request, 'Incorrect Username and Password!', extra_tags='login')
                return redirect('vorbestellenapp:contact_view')
        return redirect('vorbestellenapp:contact_view')

class AdminView(View): 
    def get(self, request):
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.filter(username="admin")
            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'Admin.html', context)
        else:
            return HttpResponse('Please login first to view this page.') 

class PriceView(View): 
    def get(self, request):
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.all()
            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'pricing.html', context)
        else:
            return render(request, 'pricing.html', {})
            

    def post(self, request):
        if request.method == 'POST':
            if 'btnLogin' in request.POST:
                username = request.POST.get('username')
                password = request.POST.get('password')
                check_password = pbkdf2_sha256.hash(password, rounds=20000, salt_size=16)
                dec_password = pbkdf2_sha256.verify(password, check_password)
                check_user = Users.objects.filter(username=username)
                if check_user and dec_password:
                    request.session['user'] = username
                    if Users.objects.filter(username=username).count()>0:
                        return redirect('vorbestellenapp:pricing_view')
                else:
                    messages.info(request, 'Incorrect Username and Password!', extra_tags='login')
                    return redirect('vorbestellenapp:pricing_view')
            elif 'btnAlpha' in request.POST:
                request.session['roomtype'] = "Alpha"
                request.session['price'] = 150.00
                return redirect('vorbestellenapp:booking_view')
            elif 'btnBravo' in request.POST:
                request.session['roomtype'] = "Bravo"
                request.session['price'] = 250.00
                return redirect('vorbestellenapp:booking_view')
            elif 'btnCharlie' in request.POST:
                request.session['roomtype'] = "Charlie"
                request.session['price'] = 350.00
                return redirect('vorbestellenapp:booking_view')
            elif 'btnDelta' in request.POST:
                request.session['roomtype'] = "Delta"
                request.session['price'] = 450.00
                return redirect('vorbestellenapp:booking_view')

        return redirect('vorbestellenapp:pricing_view')

class SignUpView(View):
    def get(self, request):
        if 'user' in request.session:
            current_user = request.session['user']
            users = Users.objects.all()
            context = {
                'current_user': current_user,
                'users' : users,
            }
            return render(request, 'signup.html', context)
        else:
            return render(request, 'signup.html', {})
    def post(self, request):        
        form = UsersForm(request.POST, request.FILES)        
        if form.is_valid():
            # try:
            username = request.POST.get("username")
            password = request.POST.get("password")
            confirmpassword = request.POST.get("cpassword")
            enc_password = pbkdf2_sha256.encrypt(password, rounds=12000, salt_size=32)
            email = request.POST.get("email")
            if(confirmpassword == password):
                if Users.objects.filter(username=username).count()>0:
                    messages.info(request, 'Username already exists!')
                    return redirect('vorbestellenapp:signup_view') 
                else:
                    form = Users(username = username, password = enc_password, email = email)
                    form.save()
                    check_user = Users.objects.filter(username=username, password=enc_password, email = email)
                    if check_user:
                        request.session['user'] = username
                        return redirect('vorbestellenapp:index_view')
            else:
                messages.info(request, 'Passwords do not match!', extra_tags='signin')
                return redirect('vorbestellenapp:signup_view')
        else:
            print(form.errors)
            messages.info(request, 'Account already exists! Please try another unique one.', extra_tags='try')
            return redirect('vorbestellenapp:signup_view')

class AccountView(View):
    def get(self, request):
        if 'user' in request.session:

vorbestellenapp/templates/portfolio-details.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Portfolio Details - Sailor Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Sailor - v4.7.0
  * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main id="main">

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container">

        <div class="row gy-4">

          <div class="col-lg-8">
            <div class="portfolio-details-slider swiper">
              <div class="swiper-wrapper align-items-center">

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-details-1.jpg" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-details-2.jpg" alt="">
                </div>

                <div class="swiper-slide">
                  <img src="assets/img/portfolio/portfolio-details-3.jpg" alt="">
                </div>

              </div>
              <div class="swiper-pagination"></div>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="portfolio-info">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong>: Web design</li>
                <li><strong>Client</strong>: ASU Company</li>
                <li><strong>Project date</strong>: 01 March, 2020</li>
                <li><strong>Project URL</strong>: <a href="#">www.example.com</a></li>
              </ul>
            </div>
            <div class="portfolio-description">
              <h2>This is an example of portfolio detail</h2>
              <p>
                Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Portfolio Details Section -->

  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

vorbestellenapp/templates/team.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Vorbestellen | Team</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <!-- <link href="assets/img/favicon.png" rel="icon"> -->
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Sailor - v4.7.0
  * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="index.html">vor<span class="highlight">best</span>ellen<span class="highlight">.</span></a></h1>
      <!-- <h1 class="logo me-auto"><a href="index.html">vorbestellen.</a></h1> -->
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="index.html">Home</a></li>

          <li class="dropdown"><a href="#"><span>About</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="about.html">About Us</a></li>
              <li><a href="team.html" class="active">Team</a></li>
              <li><a href="contact.html">Contact</a></li>
              <!-- <li><a href="testimonials.html">Testimonials</a></li> -->

              <!-- <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li> -->
            </ul>
          </li>
          <li class="dropdown"><a href="#"><span>Services</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Quick Booking</a></li>
              <!-- <li><a href="team.html">View Rooms</a></li> -->
              <!-- <li><a href="testimonials.html">Testimonials</a></li> -->
              <li class="dropdown"><a href="#" class="#"><span>Pricing</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="pricing.html" class="#">Morning</a></li>
                  <li><a href="pricing.html" class="#">Afternoon</a></li>
                  <li><a href="pricing.html" class="#">Evening</a></li>
                </ul>
              </li>

              <li class="dropdown"><a href="portfolio.html"><span>View Rooms</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Alpha</a></li>
                  <li><a href="#">Bravo</a></li>
                  <li><a href="#">Charlie</a></li>
                  <li><a href="#">Delta</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <!-- <li><a href="portfolio.html">Portfolio</a></li> -->
          <!-- <li><a href="blog.html">Blog</a></li> -->

        {% if current_user %}
        <li class="dropdown"><a href="#"><span>{{current_user}}</span> <i class="bi bi-chevron-down"></i></a>
        <ul>
          <li><a href="#">My Reservations</a></li>
          <li><a href="{% url 'vorbestellenapp:account_view' %}">Account Settings</a></li>
          <li><a href="{% url 'vorbestellenapp:logout' %}">Logout</a></li>
        </ul>
        
        {% else %}
        <li><a href="#" class="getstarted" data-toggle="modal" data-target="#exampleModalCenter">Login</a></li>
        </ul>
        {% endif %}
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>The Team</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Team</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Team Section ======= -->
    <section id="team" class="team ">
      <div class="container">

        <div class="row">

          <div class="col-lg-6">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="assets/img/team/mike.jpg" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Mikerossti Ponce</h4>
                <span>Project Manager / Back-end</span>
                <p>Aspiring Web Developer / Artist</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-6 mt-4 mt-lg-0">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="assets/img/team/otsuki.jpg" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Mcwayne Otsuki</h4>
                <span>Fullstack Developer</span>
                <p>Always has an eye for creativity with simplicity</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="assets/img/team/miko.jpg" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Mikole Rosales</h4>
                <span>Front-end and Design</span>
                <p>Quisquam facilis cum velit laborum corrupti</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div>

          <!-- <div class="col-lg-6 mt-4">
            <div class="member d-flex align-items-start">
              <div class="pic"><img src="assets/img/team/team-4.jpg" class="img-fluid" alt=""></div>
              <div class="member-info">
                <h4>Amanda Jepson</h4>
                <span>Accountant</span>
                <p>Dolorum tempora officiis odit laborum officiis</p>
                <div class="social">
                  <a href=""><i class="ri-twitter-fill"></i></a>
                  <a href=""><i class="ri-facebook-fill"></i></a>
                  <a href=""><i class="ri-instagram-fill"></i></a>
                  <a href=""> <i class="ri-linkedin-box-fill"></i> </a>
                </div>
              </div>
            </div>
          </div> -->

        </div>

      </div>
    </section><!-- End Team Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Vorbestellen</h3>
              <p>
                A108 Adam Street <br>
                NY 535022, USA<br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Vorbestellen</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/sailor-free-bootstrap-theme/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/waypoints/noframework.waypoints.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>